name: "Terraform Deployment"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write  # Required for AWS OIDC connection
  contents: read   # Required for actions/checkout
  pull-requests: write  # Required for GitHub bot to comment PR

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate SSH Key Pair
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-action-key" -f backend-key -N ""
          echo "PUBLIC_KEY=$(cat backend-key.pub)" >> $GITHUB_ENV
          echo "PRIVATE_KEY=$(cat backend-key)" >> $GITHUB_ENV

      - name: Store Private Key Securely
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/backend-key
          chmod 400 ~/.ssh/backend-key

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_KEY_NAME }}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_key_name: "backend-key"
          TF_VAR_public_key: "$PUBLIC_KEY"

      - name: Upload SSH Private Key to GitHub Artifacts (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: backend-key
          path: backend-key
          retention-days: 1  # Keep key for 1 day

      - name: Cleanup SSH Keys
        run: rm -f backend-key backend-key.pub ~/.ssh/backend-key